# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-managed-grafana-data-source-cloudwatch
  description: This component creates a CloudWatch data source in Amazon Managed Grafana
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
